defaults:
  - hydra: default.yaml
  - paths: default.yaml
  - env: HalfCheetah.yaml
  - _self_
# info
task_name: "RL"
tags: ["debug"]

output_dir: "${paths.output_dir}"
device: "cuda"
net:
  _target_: tianshou.utils.net.common.Net
  _partial_: true
  hidden_sizes: [256, 256]
  softmax: false
  device: ${device}
actor:
  _target_: tianshou.utils.net.continuous.ActorProb
  _partial_: true
  device: ${device}
actor_optim:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 3e-4
  gamma: 0.99
net_c1:
  _target_: tianshou.utils.net.common.Net
  _partial_: true
  hidden_sizes: [256, 256] # TODO more width and less depth
  concat: true
  device: ${device}
critic1:
  _target_: tianshou.utils.net.continuous.Critic
  _partial_: true
  device: ${device}
critic1_optim:
  _target_: ${actor_optim._target_}
  _partial_: true
  lr: 1e-3
  gamma: 0.99
net_c2: ${net_c1}
critic2: ${critic1}
critic2_optim: ${critic1_optim}
policy:
  _target_: tianshou.policy.SACPolicy
  # _target_: agent.sac.CustomSACPolicy
  # _target_: agent.sac.AsyncACSACPolicy
  _partial_: true
  tau: 0.005
  gamma: 0.99
  alpha: 0.2
  estimation_step: 1
train_collector:
  _target_: tianshou.data.Collector
  _partial_: true
  buffer: 
    _target_: tianshou.data.ReplayBuffer
    size: 1000000
    # buffer_num: 2
  exploration_noise: true
test_collector:
  _target_: tianshou.data.Collector
  _partial_: true
trainer:
  _target_: tianshou.trainer.OffpolicyTrainer
  _partial_: true
  max_epoch: 200
  step_per_epoch: 5000
  step_per_collect: 1
  episode_per_test: 10
  batch_size: 256
  # repeat_per_collect: 1
  update_per_step: 1
  test_in_train: false
  


